#!/bin/bash
set -e;

if [ -n "${DB_POSTGRESDB_NON_ROOT_USER:-}" ] && [ -n "${DB_POSTGRESDB_NON_ROOT_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$DB_POSTGRESDB_USER" --dbname "postgres" <<-EOSQL
		DO \$\$
		BEGIN
			IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${DB_POSTGRESDB_DATABASE}') THEN
				CREATE DATABASE ${DB_POSTGRESDB_DATABASE};
			END IF;
		END
		\$\$;
		GRANT ALL PRIVILEGES ON DATABASE ${DB_POSTGRESDB_DATABASE} TO ${DB_POSTGRESDB_USER};
	EOSQL

	psql -v ON_ERROR_STOP=1 --username "$DB_POSTGRESDB_USER" --dbname "$DB_POSTGRESDB_DATABASE" <<-EOSQL
		CREATE USER ${DB_POSTGRESDB_NON_ROOT_USER} WITH PASSWORD '${DB_POSTGRESDB_NON_ROOT_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${DB_POSTGRESDB_DATABASE} TO ${DB_POSTGRESDB_NON_ROOT_USER};
		GRANT CREATE ON SCHEMA public TO ${DB_POSTGRESDB_NON_ROOT_USER};
	EOSQL
	echo "Usuário criado com sucesso."
else
	echo "SETUP INFO: No Environment variables given!"
fi